### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10,)
print('Ветор:')
print(vector)
print('Розмірність вектора:', vector.shape)

Ветор:
[0.19867603 0.25063331 0.59367513 0.26317705 0.8734558  0.60022903
 0.20512953 0.91280964 0.42094717 0.9360846 ]
Розмірність вектора: (10,)


In [3]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print('Матриця:')
print(matrix)
print('Розмірність матриці:', matrix.shape)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмірність матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector_sum = vector + 10
print(vector_sum.round(2))

[10.2  10.25 10.59 10.26 10.87 10.6  10.21 10.91 10.42 10.94]


In [5]:
matrix_mult = np.dot(matrix, 2)
print(matrix_mult)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [6]:
vector_squared = vector**2
print(vector_squared)

[0.03947216 0.06281706 0.35245016 0.06926216 0.76292503 0.36027489
 0.04207812 0.83322145 0.17719652 0.87625437]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [9]:
print(np.dot(result_matrix, C))

[[0.5202]
 [0.2846]]


In [10]:
print(np.dot(result_matrix, D))

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [11]:
print(result_matrix.T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [12]:
print(vector)
print(vector.T)
print('Розмірність вектора:', vector.shape)
print('Розмірність транспонованого вектора:', vector.T.shape)

[0.19867603 0.25063331 0.59367513 0.26317705 0.8734558  0.60022903
 0.20512953 0.91280964 0.42094717 0.9360846 ]
[0.19867603 0.25063331 0.59367513 0.26317705 0.8734558  0.60022903
 0.20512953 0.91280964 0.42094717 0.9360846 ]
Розмірність вектора: (10,)
Розмірність транспонованого вектора: (10,)


**Немає змін між вектором та транспонованим вектором, бо вектор - одновимірний**

In [13]:
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
print(vector)
print('Розмірність вектора column_vector', column_vector.shape)
print('Розмірність вектора vector', vector.shape)

[[0.19867603]
 [0.25063331]
 [0.59367513]
 [0.26317705]
 [0.8734558 ]
 [0.60022903]
 [0.20512953]
 [0.91280964]
 [0.42094717]
 [0.9360846 ]]
[0.19867603 0.25063331 0.59367513 0.26317705 0.8734558  0.60022903
 0.20512953 0.91280964 0.42094717 0.9360846 ]
Розмірність вектора column_vector (10, 1)
Розмірність вектора vector (10,)


In [14]:
print(column_vector.T)
print('Розмірність вектора, транспонованого до вектора column_vector', column_vector.T.shape)

[[0.19867603 0.25063331 0.59367513 0.26317705 0.8734558  0.60022903
  0.20512953 0.91280964 0.42094717 0.9360846 ]]
Розмірність вектора, транспонованого до вектора column_vector (1, 10)
